### ISSUE TITLE
KeyError: 'sub'

### ISSUE THREAD

**Issue by ifynk** [mmcloughlin/reprotobuf#1]
Tried to use your script with Google Play app and got this error

> Traceback (most recent call last):
>   File "reprotobuf.py", line 246, in <module>
>     workspace.structure_packages()
>   File "reprotobuf.py", line 62, in structure_packages
>     for name in self.tree['sub']:
> KeyError: 'sub'

**Comment by FrankPortman** [comment]
+1

**Comment by dimmduh** [comment]
+1 same error

But next I tryed with another apk
And got this error: 

```
reprotobuf.py", line 241, in analyze
    assert 'tag' in properties
AssertionError
```

**Comment by FrankPortman** [comment]
Still getting this. Please fix...

**Comment by spiside** [comment]
+1 same error

**Comment by mmcloughlin** [comment]
@dimmduh Which APK did you get this error with?

**Comment by dimmduh** [comment]
@mmcloughlin I tried google play 6.9.20, 5.9.12, 4.2.3

**Comment by ifynk** [comment]
I tried this apk.
[com.android.vending-1.apk.zip](https://github.com/mmcloughlin/reprotobuf/files/531597/com.android.vending-1.apk.zip)

**Comment by mmcloughlin** [comment]
@ifynk In that APK the generated classes are obfuscated. The script currently identifies protobuf classes by looking for classes that extend `MessageNano`. This base class is actually `com.google.protobuf.nano.b` in that APK. The root cause of your error is that it's not actually finding any classes.

Even more discouraging is the fact that the message classes themselves have been obfuscated. Reverse engineering is still possible via this method (looking for classes extending `b` instead), but we'd end up with an obfuscated schema also.

**Comment by mfonville** [comment]
an obfuscated schema is still useful though, since we already know the majority of the schema from older versions, and could re-puzzle what changed in the schema with each update ;-)

Would it be possible to reliably detect what obfucsated base class name matches the  `MessageNano` and finding the extended classes still with the python script?

the proto-interpretation would then be a job for humans.

**Comment by mmcloughlin** [comment]
Let me look into whether I can identify the obfuscated `MessageNano` class.

**Comment by avaidyam** [comment]
Any progress with this? I'm getting the same issue.

**Comment by FrankPortman** [comment]
Where are we at with this @mmcloughlin

**Comment by APTy** [comment]
+1

**Comment by jvaill** [comment]
+1

**Comment by yl2chen** [comment]
-1

**Comment by spiside** [comment]
Hey! Sorry to bug you, just wondering if there would be an update regarding this issue. Cheers!

**Comment by dkbarn** [comment]
+1

**Comment by ReimarPB** [comment]
Any updates on this?
